### ISSUE TITLE
部分网站中文乱码，请问怎么解决？

### ISSUE THREAD

**Issue by 418623336** [yale8848/CacheWebView#1]
比如http://m.mm131.com/xinggan/3320_2.html这个网页，原生webview是能正常显示的

**Comment by 418623336** [comment]
对了，上面这个网站有反爬机制，直接打开的话，中间会显示成QQ的图片，但是原生WebView和其他浏览器显示是正常的

**Comment by yale8848** [comment]
嗯 ，看到了，谢谢你的反馈，是编码问题，我正在解决中...

**Comment by yale8848** [comment]
请更新至1.0.0再试一下

**Comment by 418623336** [comment]
编码的问题已经解决了，这个网站的图片也可以显示了（事实上之前只是直接打开的页面图片不显示，点击页面内链接，后续网页的图片都很正常）。
但是我发现新版的磁盘缓存里并没有缓存图片，似乎缓存的文件少了很多，且不仅仅是这一个网站（有些网站还是有缓存图片的），不知道是改了哪里的设置……
我现在最看中的就是图片缓存功能了，因为这样保存图片的时候可以直接从

**Comment by 418623336** [comment]
直接从缓存里获取，之前在网上查了很多资料，都没有找到从原生WebView里获取到缓存图片的方法……

**Comment by yale8848** [comment]
你更新至1.0.1 再试试，同时针对你的需求我添加了getCacheFile(URL) 函数，你可以看看readme

**Comment by yale8848** [comment]
你更新至1.0.2 再试试，同时针对你的需求我添加了getCacheFile(URL) 函数，你可以看看readme

**Comment by 418623336** [comment]
这下终于完美解决了，非常感谢！～～ps：好像现在1.0.2版没有更新到代码库
