### ISSUE TITLE
这个CacheWebView最大支持多大的缓存？Android的默认WebView缓存有多大？

### ISSUE THREAD

**Issue by AthlanLiu** [yale8848/CacheWebView#100]
Mobile:  

Android OS: 

NetWork: 

URL: 

LIB Version: 

---

如题，Android的WebView是Chrome核，理论上也是可以设置并支持大缓存的。这个库的优势上写着突破缓存限制，那么限制是多少呢？突破到多少呢？

**Comment by yale8848** [comment]
Chrome内核限制最大应该是剩余空间1/8，这个大小是不能设置的；
这个库可以设置缓存大小，没有上限；

**Comment by AthlanLiu** [comment]
以现在动不动就16G以上的Android设备来讲，剩余空间的1/8已经完全足够绝大多数的页面缓存了。看了介绍，这个CacheWebView默认是200M，当然可以手动设置。不过也小于系统WebView支持的

**Comment by yale8848** [comment]
嗯嗯 你说的有道理
