### ISSUE TITLE
【建议】  在 checkUrl 增加一个可以自定义回调

### ISSUE THREAD

**Issue by 1847211504** [yale8848/CacheWebView#101]
应用场景是这样的，某些情况下可能需要自定义控制这个 url 走缓存还是网络请求，比如我们的应用中，有一部分配置是 js 的，静态缓存 js 的时候就会导致配置更改后无法更新，但还不适用于您之前提过的，在前端引用名称中增加可变 md5 之类的 hash，还有假如文件成千上万，都需要通过改引用文件名更改的话，麻烦也浪费不必要的流量，因为仅仅是更改了配置 js，html 和基础 js 并没有变，

所以，假如在 检测 前增加一个自定义规则，如果规则不允许缓存，则优先处理，不知道您有没有更好更灵活的方案？

//....
private boolean checkUrl(String url){
        if (TextUtils.isEmpty(url)) {
            return false;
        }
        if (!url.startsWith("http")) {
            return false;
        }
    
       //新增的自定义规则，可以是文件名，可以是 url，我们是用文件名判断的
       if(null != customChecker && !customChecker.check(url))
         return false;

        String extension = MimeTypeMapUtils.getFileExtensionFromUrl(url);
        //........原来的按扩展判断
｝

**Comment by yale8848** [comment]
请更新：compile 'ren.yale.android:cachewebviewlib:2.0.3'

```
    builder.setResourceInterceptor(new ResourceInterceptor() {
            @Override
            public boolean interceptor(String url) {
                return true;//按照默认规则，false 不拦截资源
            }
        });
```

**Comment by 1847211504** [comment]
收讫，感恩
