### ISSUE TITLE
缓存失败的问题

### ISSUE THREAD

**Issue by raulbest** [yale8848/CacheWebView#105]
你好，我有个问题，我们自己实现的WebView缓存的功能，看了下，和你的大致思路差不多。但是遇到了一个偶发性的问题，就是我们每次会先判断是否有缓存文件，有的话就加载，没有的话就先缓存再加载，现在就有个问题，如果在缓存的过程中，由于某些不确定的因素，导致某个资源（比如JS）没有缓存成功，这个时候页面就会加载不出来。不知道你这个CacheWebView在这个地方是怎么处理的？谢谢

**Comment by yale8848** [comment]
1.x 的时候是我自己实现下载功能的，发现问题比较多，2.x的时候用完全交给okhttp去下载缓存，缓存处理也妥妥的交给okhttp了；如果出现下载失败，都没有办法，webview也是同样的问题；如果不是自身bug引起的下载错误，这个是正常的；

**Comment by raulbest** [comment]
嗯，好的。刚上面那个问题场景我描述得不够具体，就是当某个资源文件（比如是aaa.js）缓存（下载）不成功的时候，可能只是下载了一部分资源(aaa.js这个资源只下载了60%)，就断掉了，但是在缓存文件夹中是有这个缓存文件的，但是不是完整的文件。下次重新进入这个H5页面的时候，假设还是这个aaa.js资源，因为上次已经缓存过了，直接从缓存文件夹中读取了那个不完整的文件，直接就导致页面加载不出来了，这个问题，你那边有做什么相应的处理策略么？谢谢

**Comment by yale8848** [comment]
你说的问题比较常见，一般处理方式是先把下载文件放在tmp目录，如果下载完成并成功，那就copy到cache目录，如果失败就不要copy了，每次从cache里拿缓存文件

**Comment by Jiiiiiin** [comment]
还是需要一个类似sql事务一样的机制，做一个确切的落地标识吧，没下载完 那就重头再来咯 ：）
