### ISSUE TITLE
请问可以动态切换缓存文件的缓存目录吗

### ISSUE THREAD

**Issue by 505541778** [yale8848/CacheWebView#114]
Mobile:  

Android OS: 

NetWork: 

URL: 

LIB Version: 

---

**Comment by 505541778** [comment]
比如加载a网站用a目录  b网站用b目录

**Comment by yale8848** [comment]
目前缓存公用一个目录，这样好处是一些公共库只缓存一次，效率更高；你这边切换缓存目录的目的是啥？

**Comment by 505541778** [comment]
因为我这所有的请求都走本地的代理  导致可能出现2个不同的css  但是  都是127.0.0.1/3452/ssss.css这种路径 因为会指向不同的远端Server地址
