### ISSUE TITLE
demo里面清理缓存以后再切换url会出现crash

### ISSUE THREAD

**Issue by tongzhaoxin** [yale8848/CacheWebView#117]
Mobile:  XiaoMi5 

Android OS: 7.0 

NetWork: WiFI

URL: https://www.baidu.com 

LIB Version:  ren.yale.android:cachewebviewlib:2.1.0

demo里面清理缓存以后再切换url会出现crash，我看日志是在AssetsLoader类的getAssetFileStream(String path)方法里报了空指针错误

**Comment by yale8848** [comment]
收到，已经修改，请更新至2.1.1
