### ISSUE TITLE
同步加载资源问题

### ISSUE THREAD

**Issue by liudg** [yale8848/CacheWebView#122]
您好，看了你的代码学习了很多。也产生了一点疑问。
网页js加载是讲究顺序的，所以只能用okhttp的同步请求方法，假如一个js很大，加载时间超过5s，是不是就会造成android ANR错误呢？没有去验证，冒昧问一下哈哈哈

**Comment by yale8848** [comment]
webview下载JS是多线程下载的，最后调用okhttp也是在线程里，不会影响到UI线程，也就不会造成ANR

**Comment by liudg** [comment]
好的，明白了，谢谢
