### ISSUE TITLE
2.1.3 加载Demo链接后崩溃

### ISSUE THREAD

**Issue by forJrking** [yale8848/CacheWebView#124]
最新版本2.1.3

12-21 16:17:58.881 8647-8665/ren.yale.android.cachewebview A/chromium: [FATAL:jni_android.cc(233)] Check failed: false. Please include Java exception stack in crash report
    
    
    --------- beginning of crash
12-21 16:17:58.997 8708-8665/? A/google-breakpad: -----BEGIN BREAKPAD MICRODUMP-----
12-21 16:17:58.997 8708-8665/? A/google-breakpad: V WebView:51.0.2704.106
12-21 16:17:58.997 8708-8665/? A/google-breakpad: O A arm 04 armv7l oneplus/bacon/A0001:6.0.1/MOB31E
12-21 16:17:58.997 8708-8665/? A/google-breakpad: G OpenGL ES 3.0 V@140.0 AU@ (GIT@Ia6c73e7530)|Qualcomm|Adreno (TM) 330
12-21 16:17:58.998 8708-8665/? A/google-breakpad: S 0 A027FC48 A027F000 00002000

**Comment by yale8848** [comment]
能给更多错误信息吗？

**Comment by forJrking** [comment]
两台手机都出现一样的崩溃信息，显示是 native 异常。2.1.2版本没有问题

**Comment by yale8848** [comment]
收到，2.1.3 改出的问题，已经修复，请更新至2.1.4试试
