### ISSUE TITLE
请问一下okhttp是怎么保存资源到缓存目录，并以0， 1结尾的

### ISSUE THREAD

**Issue by yunshuipiao** [yale8848/CacheWebView#129]
LIB Version: 

---

请问一下okhttp是怎么保存资源到缓存目录，并以0， 1结尾的？
OKHttpFile. getCacheFile() 方法中读取okhttp的缓存文件，想知道okhttp是怎么保存的，愿那里面没找到。

**Comment by yale8848** [comment]
0结尾的是存储http header 信息，1结尾的是源文件或者压缩的文件，具体存储方式用的是DiskLruCache.java，缓存流程你可以看看Cache.java
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.java
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Cache.java

**Comment by yunshuipiao** [comment]
@yunshuipiao 多谢，今天大概看了一下，明天仔细看看
