### ISSUE TITLE
更新web中的图片之后 图片不缓存的问题

### ISSUE THREAD

**Issue by changtuixiaopangdun** [yale8848/CacheWebView#142]
我先在 splash界面加载了webview  缓存资源 再在首页显示 第一次进入app 可以很好显示 如果改了图片列表 第二次进入首页需要加载图片

**Comment by yale8848** [comment]
强制缓存设置了吗？.setCacheType(CacheType.FORCE);

**Comment by changtuixiaopangdun** [comment]
默认的 没改

**Comment by yale8848** [comment]
请提供一下测试链接看看
