### ISSUE TITLE
缓存路径下找不到缓存文件

### ISSUE THREAD

**Issue by liuhuiAndroid** [yale8848/CacheWebView#143]
Application设置了缓存路径，多次加载WebView后确实有缓存效果，但是缓存路径下没有内容。
Application设置缓存路径代码：

        // CacheWebview 基本设置
        val builder = WebViewCacheInterceptor.Builder(mContext)
        val file = File(mContext.externalCacheDir, "CacheWebViewCache")
        if (!file.exists()) {
            file.mkdirs()
        }
        builder.setCachePath(file)//设置缓存路径，默认getCacheDir，名称CacheWebViewCache
            .setCacheSize((1024 * 1024 * 100).toLong())//设置缓存大小，默认100M
            .setConnectTimeoutSecond(20)//设置http请求链接超时，默认20秒
            .setConnectTimeoutSecond(20)//设置http请求链接超时，默认20秒
            .setReadTimeoutSecond(20)//设置http请求链接读取超时，默认20秒
            .setCacheType(CacheType.NORMAL)//设置缓存为正常模式，默认模式为强制缓存静态资源
        WebViewCacheInterceptorInst.getInstance().init(builder)

**Comment by liuhuiAndroid** [comment]
TAG=CacheWebView的日志都没打印，很奇怪

**Comment by liuhuiAndroid** [comment]
日志都没打印，也没有报错，是集成失败了吗？但是功能没啥问题

**Comment by liuhuiAndroid** [comment]
下面是最终修改成代码，除了File我代码有误，不知道哪个参数设置不对会初始化失败：

        val builder = WebViewCacheInterceptor.Builder(mContext)
        builder.setCachePath(File(mContext.externalCacheDir.toString(), "CacheWebViewCache"))
        WebViewCacheInterceptorInst.getInstance().init(builder)

**Comment by yale8848** [comment]
1.只要访问路径存储并权限够，cache路径配置应该是成功的，我这测试都没有问题；
2.TAG日志没有打印就证明是没有走cache拦截，这个问题你具体根据你的访问url debug断点至WebViewCacheInterceptor.interceptRequest找找问题所在；
