### ISSUE TITLE
您好，使用了强制缓存模式后，如果需要更新静态资源，能具体说说怎么做么？

### ISSUE THREAD

**Issue by xq598359628** [yale8848/CacheWebView#15]
如题。客户端需要具体怎么做呢？能提供一个demo么？

**Comment by yale8848** [comment]
这个需要web前端改，如果web前端用打包工具如grunt,webpack等都可以在链接后面加一个md5成为一个新的链接，这种做法是目前通用的做法，web前端的同学肯定知道的

**Comment by xq598359628** [comment]
意思就是客户端什么也不用处理。客户端碰到新的链接就去重新下载并且缓存了 是么？

**Comment by yale8848** [comment]
嗯嗯，是的，客户端不用做任何处理

**Comment by xq598359628** [comment]
谢谢啦
