### ISSUE TITLE
mp4

### ISSUE THREAD

**Issue by taiyangmobile** [yale8848/CacheWebView#152]
你好：
       我的连接中有一个mp4文件，发现没有缓存，链接地址是
http://box.test.huacai.com:8200/media/uploads/program/2018/201812/20181218105453_28694_1.mp4
代码中已填加extension.addExtension("mp4");    debug发现此语句已经执行，测试中在cache_path_name也没有发现缓存的文件信息，其他网页的静态图片可以缓存。请帮忙检查一下mp4没有缓存可能是什么问题，谢谢。

**Comment by yale8848** [comment]
CacheWebView 无法从Android浏览器内核获取动态多媒体流，所以无法处理多媒体缓存，如下都不会缓存：
```
private static HashSet NO_CACH = new HashSet() {
        {
            add("mp4");
            add("mp3");
            add("ogg");
            add("avi");
            add("wmv");
            add("flv");
            add("rmvb");
            add("3gp");
        }
    };
```

**Comment by taiyangmobile** [comment]
1，你的意思是技术上做不到是吗？
2，请问，webview本身的缓存机制也无法缓存mp4文件吗？

**Comment by yale8848** [comment]
技术上可行，可以参考 https://github.com/danikula/AndroidVideoCache 代理实现，目前CacheWebView不关注视频缓存；
