### ISSUE TITLE
为什么要把系统缓存也开启

### ISSUE THREAD

**Issue by cyy2yjp** [yale8848/CacheWebView#16]
发现这个框架同时开启了系统缓存和自定义缓存 ，关掉系统缓存后，部分图片无法显示  ，  也没有使用异步缓存

**Comment by yale8848** [comment]
开启系统缓存主要目的是有网时也能缓存CacheWebView没有匹配的资源，这样断网访问的话，资源都能从缓存拿；CacheWebView匹配的资源从CacheWebView缓存拿，没有匹配到的从系统拿，两个不冲突；你可以自定义关掉系统缓存；
你说的部分图片无法显示的问题，请详细情况说一下：

Mobile:

Android OS:

NetWork:

URL:

LIB Version:

**Comment by cyy2yjp** [comment]
额 是这样啊  图片没显示 代码逻辑问题 ，两个不冲突的啊， 这样就放心了 ，谢谢作者
