### ISSUE TITLE
shouldOverrideUrlLoading无法被回调

### ISSUE THREAD

**Issue by tp19970424** [yale8848/CacheWebView#164]
Mobile:  

Android OS: 

NetWork: 

URL: 

LIB Version: 

---

为什么使用了WebViewCacheInterceptorInst.getInstance().interceptRequest(request);以后，webview自带的shouldOverrideUrlLoading方法就回调不出来了？我就拿不到当前的url了

**Comment by tp19970424** [comment]
Mobile: XiaoMi9

Android OS: 9.0

NetWork: WiFI

LIB Version: ren.yale.android:cachewebviewlib:2.1.8

为什么使用了WebViewCacheInterceptorInst.getInstance().interceptRequest(request);以后，webview自带的shouldOverrideUrlLoading方法就回调不出来了？我就拿不到当前的url了，无法做其他的操作了

**Comment by yale8848** [comment]
shouldOverrideUrlLoading 应该不受影响的，请贴一下代码我这边看看

**Comment by tp19970424** [comment]
抱歉，我解决了，是自己使用不规范的缘故，不好意思啊
