### ISSUE TITLE
使用assert本地资源后  从网页加载资源会报跨域问题：

### ISSUE THREAD

**Issue by chengyoujie** [yale8848/CacheWebView#169]
Mobile:  Mumu模拟器

Android OS: 

NetWork: 

URL: https://cdn-ns-studio.uuzuonline.com/product-4006701/cdn1/res/qufuResource/assets/atlas/xingxing1_ef2fc801.json

LIB Version: 

---

使用assert本地资源后  从网页加载资源会报跨域问题：
XMLHttpRequest cannot load https://cdn-ns-studio.uuzuonline.com/product-4006701/cdn1/res/qufuResource/assets/atlas/xingxing2_7a72cf4d.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://nslmh5api.youzu.com' is therefore not allowed access.", source: https://nslmh5api.youzu.com/web/yzwd/index.php?token=eyJvc2RrX2dhbWVfaWQiOiIxOTYzNzc5MDEiLCJ1c2VyX2lkIjoiNDciLCJsb2dpbl9zZGtfbmFtZSI6IkRlbW8iLCJjaGFubmVsX2lkIjoiMCIsImV4dGVuZCI6IjIxNTB8NDAwNjcwMXxvcGdhbWVpZCIsImFjY291bnRfc3lzdGVtX2lkIjoiMDA2MDAwMCIsIm9zZGtfdXNlcl9pZCI6IjAwNjAwMDBfNDciLCJpcCI6IjU4LjI0Ni4yMzIuMTgiLCJjb3VudHJ5IjoiQ04iLCJ0aW1lIjoxNTgyNzk2MzQ3LCJzaWduIjoiZGViNDBlMjUzZTU2NDcyNzc0NDVlZGZhNzAxMDhjODQifQ==&version=1.0.0 (0)
02-27 17:39:06.780 14870-14870/com.byh I/chromium: [INFO:CONSOLE(0)]

**Comment by AngelBo** [comment]
file协议不支持跨域

**Comment by xiaoxiaozero** [comment]
可以给WebResourceResponse的header头添加设置"Access-Control-Allow-Origin", "*"   就行了

**Comment by chengyoujie** [comment]
已解决， 谢谢了😀
