### ISSUE TITLE
assets里的缓存资源是写死的么，能否支持动态下发重置？

### ISSUE THREAD

**Issue by po1arbear** [yale8848/CacheWebView#184]
如题

**Comment by yale8848** [comment]
目前不支持，如果要支持动态下发，你可以自己实现

**Comment by po1arbear** [comment]
assets文件夹只能读不能写吧，这样是不是没法替换了，只能自己指定文件夹缓存静态资源，这样改动会比较大

**Comment by po1arbear** [comment]
https://github.com/yale8848/CacheWebView/pull/186

**Comment by yale8848** [comment]
十分感谢pr，已经更新
