### ISSUE TITLE
您好，我想请教一个预加载问题

### ISSUE THREAD

**Issue by diguagege** [yale8848/CacheWebView#188]
您好，目前我想做基于您这套缓存去做一个预加载。想通过提前下载一个GZip文件，并解压缩到咱们的CacheWebViewCache目录下。
目前看咱们的文件都是通过url去存储，但是下载下来的gzip解压后可能只有文件名同url的文件名一致，没有前面的前缀，想问问有没有什么方案处理呢？
期待您的回复

**Comment by yale8848** [comment]
应该可以实现的，你可以修改一下库，可以把http判断兼容`file://`方案

**Comment by diguagege** [comment]
> 应该可以实现的，你可以修改一下库，可以把http判断兼容`file://`方案

抱歉，才看到回复。
我已经搞定了，具体的做法是，通过Okhttp下载一个gzip包，解压缩到咱们的CacheWebViewCache目录下，然后在interceptRequest的时候，通过url，以特定方式去匹配不同项目中的文件数据，最终返回一个WebResourceResponse。
