### ISSUE TITLE
建议将CacheWebViewClient改为public

### ISSUE THREAD

**Issue by 418623336** [yale8848/CacheWebView#2]
覆盖onpagefinished事件是一个常见的需求，定义成final就没法改了。
另外有些网站的css会失效，比如手机版github……

**Comment by 418623336** [comment]
还有一个问题，所有的输入框都失效了，没有办法弹起虚拟键盘

**Comment by yale8848** [comment]
你正常setWebViewClient就行，我是处理过的，onpagefinished会收到消息的；
输入框失效的问题已经修复，请更新至1.0.3
css 失效的问题我再看看
