### ISSUE TITLE
播放缓存MP4文件报错

### ISSUE THREAD

**Issue by lijijordan** [yale8848/CacheWebView#22]
![image](https://user-images.githubusercontent.com/3657235/33659820-9833357e-dabc-11e7-81b7-116a43a17dd4.png)
视频地址：https://s3.cn-north-1.amazonaws.com.cn/mxjwebsite/smartoffice-public/mscreen/screen_test.mp4

**Comment by yale8848** [comment]
你使用最新版本测试的吗？ren.yale.android:cachewebviewlib:1.2.7
mp4文件不会缓存的，目前CacheWebView不支持多媒体缓存的

**Comment by lijijordan** [comment]
我改了一下，想用来缓存mp4文件，但是缓存成功了一部分，感觉没有把完整的流都保存下来。
`if (extension.toLowerCase().equals("js") ||
                extension.toLowerCase().equals("css") ||
                extension.toLowerCase().equals("mp4")) {
            return true;
        }`  

这个encode是用来干啥呢？
`if (mStaticRes.isCanGetEncoding(extension)&&TextUtils.isEmpty(encoding)){
                    InputStreamUtils inputStreamUtils = new InputStreamUtils(resourseInputStream.getInnerInputStream());
                    inputStreamUtils.setEncodeBufferSize(CacheConfig.getInstance().getEncodeBufferSize());
                    long start = System.currentTimeMillis();
                    InputStream copyInputStream = inputStreamUtils.copy(mEncodingDetect);
                    if (copyInputStream == null){
                        return null;
                    }
                    resourseInputStream.setInnerInputStream(copyInputStream);
                    encode = inputStreamUtils.getEncoding();
                    CacheWebViewLog.d(encode+" "+"get encoding timecost: "+(System.currentTimeMillis()-start)+ "ms "+url);
                }`

**Comment by yale8848** [comment]
encode是判断html,js,css文件编码的，我当初设计的时候就没有给多媒体文件设计缓存，如果你给视频添加缓存的话是会失败的

**Comment by yale8848** [comment]
流媒体的一般通过设置代理实现缓存，你可以 参考参考这个库 https://github.com/danikula/AndroidVideoCache

**Comment by lijijordan** [comment]
OK 谢啦！
