### ISSUE TITLE
无法设置某个默认扩展名文件的缓存

### ISSUE THREAD

**Issue by libinliu2013** [yale8848/CacheWebView#24]
Mobile:  

Android OS: 

NetWork: 

URL: 

LIB Version: 

---

应该是手误吧？
StaticRes.java ->remove方法78行
        extension = extension.replaceAll(".","");

**Comment by libinliu2013** [comment]
哦， 行数和库里面代码对不上，另外好几个地方都写成了replaceAll

**Comment by libinliu2013** [comment]
对了， 还有一个问题， 刚开始学习webview使用， 暂时没找到原因，问题如下：
访问html页面的时候， 会造成onPageFinished调用两次。
----------
这个问题带来的影响是我集成了CacheWebView和jsbridge，使的jsbridge没法初始化成功,具体原因也没有找到、、、有时间再找找。

**Comment by libinliu2013** [comment]
加载两次的问题找到了， CacheWebViewClient的shouldOverrideUrlLoading方法中：
`@Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {

        if (mCustomWebViewClient!=null){
            boolean load =  mCustomWebViewClient.shouldOverrideUrlLoading(view,url);
            if (!load){

                view.loadUrl(url);
            }
            return load;//这里是错误的, 如果load为false, 上面if里面已经处理了，这里应该返回true
        }
        view.loadUrl(url);
        return true;
    }`

**Comment by yale8848** [comment]
谢谢你的问题反馈，这两个问题都已经修改，请更新到最新版本

**Comment by libinliu2013** [comment]
:)速度真快，建议直接集成jsbridge进去，大部分用webview都会需要js和原生通讯的能力，并且因为cachewebview和jsbridge都是直接继承webview的方式来实现，造成像我这种初学者集成会花费比较多的时间。 
甚至更进一步，我建议集成加载进度条、常用的原生控件(例如定位、扫码、拍照、上传等)，项目后期的发展空间会更大。
