### ISSUE TITLE
希望添加强制刷新的功能

### ISSUE THREAD

**Issue by mix-future** [yale8848/CacheWebView#28]
现在资源缓存之后好像就只能按照过期时间来进行管理，如果资源加载出了问题，就没有办法强制刷新，webview设置load_no_cache也没用。感觉应该在force和normal后面再加一个模式，强制不加载本地缓存，从而更新资源

**Comment by mix-future** [comment]
最好是能跟原生webview的几个模式对应起来，也便于理解，目前我的理解是forece对应load_cache_else_network，normal对应load_default

**Comment by yale8848** [comment]
1.我写CacheWebView的目的就是要强制缓存**静态资源** ，这样是为了加速访问，注意非静态资源不缓存，除非你主动添加了后缀映射；
2.如果要更新资源的话建议还是让前端或后台人员去修改访问链接，这样新的链接就会从服务端拉取；
3.对于css，js，图片等静态资源如果开启强制缓存，就是直接从缓存拿，但是html我还是以通过http缓存判断有更新了再从服务器拿数据的；
4.对于有些特殊需要刷新的静态资源可以通过下面的接口设置是否缓存
```
webview.setCacheInterceptor(new CacheInterceptor() {
            public boolean canCache(String url) {
                return true;
            }
 });
```

**Comment by mix-future** [comment]
额，我说一个情况吧，用户网络不好，图片只加载了一半，如果没有手动刷新的功能，这张图就一直显示不完整了。这个接口虽然可以起到刷新的作用，但是用户肯定是按照页面来刷新，页面里面有哪些资源是不太好确定的

**Comment by yale8848** [comment]
请更新至1.3.1，添加webview.setCacheStrategy(WebViewCache.CacheStrategy.NO_CACHE)强制刷新模式

**Comment by mix-future** [comment]
更新的好快！作者辛苦了！

**Comment by mix-future** [comment]
对了，我看WebView默认的缓存是采用_0这种格式结尾的，而这个库采用的是.0这种后缀名来结尾。但是读取数据的时候，事实上创建snapshot之后每次也只读取了一种类型的文件，也就是说并没有发挥出一个key对应多个文件的优势。这种情况下手动给key加上后缀名、实现一一对应不知道效率会不会更高一些？（我还没有测试过，如果效率差不多，那就没必要改）

**Comment by mix-future** [comment]
哦，我理解有问题，还是统一用一个key管理起来要更方便

**Comment by yale8848** [comment]
这块用一个key+index的方式实现一个key对应多个文件的，个人觉得这样也挺方便的
