### ISSUE TITLE
发现两个网站字符乱码

### ISSUE THREAD

**Issue by 418623336** [yale8848/CacheWebView#3]
http://m.dmzj.com/info/zaidiyubianyuannahan.html 动漫之家的介绍页面乱码；
http://ubook.qq.com/8/index.html QQ阅读首页一些字符，比如“书架”、“登录”、“退出”之类的乱码。
麻烦作者有空看看是怎么回事呢～～

**Comment by 418623336** [comment]
动漫之家的乱码很诡异，有时候第一次看乱码，再加载一次，部分字符又正常了……

**Comment by yale8848** [comment]
编码判断有问题，我再看看

**Comment by yale8848** [comment]
你更新到1.0.4再看看

**Comment by 418623336** [comment]
现在没问题了，作者好勤奋～～

**Comment by yale8848** [comment]
哈哈，还得多谢你的宝贵反馈啊！你也很勤奋啊，睡的这么晚~~

**Comment by 418623336** [comment]
试用了一个星期，感觉非常好用。体验上不输原生WebView，但却有强大的多的缓存功能。调用也非常简单，几乎不用配置，作者真的很用心～～

**Comment by yale8848** [comment]
谢谢你的使用，还有很多地方需要优化，有啥问题了随时反馈哦😁
