### ISSUE TITLE
对源码的一点质疑，关于资源的 referer

### ISSUE THREAD

**Issue by mylovemaliang** [yale8848/CacheWebView#30]
Mobile:   all

Android OS: all

NetWork: WiFI/3G/4G/5G 

URL:  all 

LIB Version:  源码 

---
源码里有关资源的referer的获取有些问题，如果页面不是通过 loadUrl 主动加载,比如页面内点击一个url，请求资源的referer就会丢失，有可能造成访问问题。

**Comment by yale8848** [comment]
是要loadUrl才行的，我修改了shouldOverrideUrlLoading逻辑。试试1.3.2，默认就会调loadUrl

**Comment by mix-future** [comment]
目前refer仍然存在一点问题，就是如果我主动加载一个JavaScript，那么后续的refer就变成这个js了，应该屏蔽掉js才行～～

**Comment by yale8848** [comment]
收到，这个问题忽略了

**Comment by yale8848** [comment]
1.3.3 已经修复了
