### ISSUE TITLE
关于终止加载的问题

### ISSUE THREAD

**Issue by mix-future** [yale8848/CacheWebView#33]
Mobile:  

Android OS: 

NetWork: 

URL: 

LIB Version: 

---

好像这个库没有重写停止加载的功能？如果在加载过程中停止、后退、刷新或者点击新链接，就会出现长时间等待。
我尝试在停止加载时主动中断当前httpurlconnection，但是只能终止一个连接而已，后续的资源仍然会加载，感觉有点困惑，不知道该怎么改了（不太清楚原生内核的stoploading都干了些什么工作……）
测试页面可以用360搜索，或者手机乐园官网

**Comment by mix-future** [comment]
晕，填的测试信息都不见了，测试链接可以用http://m.so.com，或者http://wap.shouji.com.cn

**Comment by mix-future** [comment]
又测了一下，手机乐园好像没问题，终止之后就没有后续资源了。但360搜索确实会一直加载后续资源，不知道是不是跟网页的设计有关系

**Comment by yale8848** [comment]
收到，我这边测试测试，按道理目前webview是单线程加载资源的，停止以后应该不会再有新的链接

**Comment by yale8848** [comment]
测试没有问题，http://m.so.com 这个是360页面自己的问题，它的网站轮询执行加一个 一像素图片的链接，估计是为了保活

**Comment by mix-future** [comment]
原来如此……多谢了！怪不得觉得360好诡异，一直跳log，我说哪来的那么多资源
