### ISSUE TITLE
使用 loadDataWithBaseURL 无法自适应屏幕

### ISSUE THREAD

**Issue by chowaikong** [yale8848/CacheWebView#34]
Mobile:  all

Android OS: all

NetWork: all

URL: none

LIB Version: 1.3.3

---

我的需求是要加载 HTML 标签而不是 URL，所以我需要使用 loadDataWithBaseURL，在原生的 WebView 是可以做到自适应屏幕，包括字体、图片等，但是 CacheWebView 使用 loadDataWithBaseURL 这个方法出来的效果就跟在电脑的浏览器模拟移动设备一样，字体、图片都非常小，既然 CacheWebView 是继承于原生的 WebView 为什么会有差别呢，是否做了其他处理？
我只是将 CacheWebView 放在 xml，然后调用 loadDataWithBaseURL，没有其他配置。

**Comment by yale8848** [comment]
谢谢反馈，我这边测试测试，应该对于这个接口处理有问题

**Comment by mix-future** [comment]
你的配置有问题，这个库默认 webSettings.setUseWideViewPort(true)，就是模拟电脑宽屏的，你设置成false，或者网页的header里设定一下viewport就行了

**Comment by chowaikong** [comment]
@mix-future 我用原生的 WebView 也没有修改 settings，显示出来直接就是自适应的。

**Comment by chowaikong** [comment]
@mix-future 明白你的意思了，这个库在 initSettings 里面的确 setUseWideViewPort(true)，改为 false 就正常了。

**Comment by yale8848** [comment]
你可以重新调用setUseWideViewPort函数覆盖本库里的设置
