### ISSUE TITLE
有时候缓存了，课件加载就变大了，不能缩放了

### ISSUE THREAD

**Issue by lyqaiym** [yale8848/CacheWebView#35]
Mobile:  

Android OS: 

NetWork: 

URL: 

LIB Version: 

---

**Comment by yale8848** [comment]
能否说具体一下：课件加载就变大了？
不能缩放是我库里默认把缩放关掉了，你可以再打开覆盖库的配置；

**Comment by lyqaiym** [comment]
https://live.xueersi.com/Live/coursewareH5/121053/1/2

**Comment by lyqaiym** [comment]
https://live.xueersi.com/Live/coursewareH5/121053/1/2  这个地址，覆盖库的配置 是哪个？

**Comment by 1398113530** [comment]
是指initSettings吗？亲测改了也没用……照样缩放不了。

**Comment by yale8848** [comment]
setUseWideViewPort(false);
