### ISSUE TITLE
缓存控制还有很大的问题

### ISSUE THREAD

**Issue by 1398113530** [yale8848/CacheWebView#37]
我想实现WebView仅缓存图片，可用CacheWebView实现起来并不顺利。
1、不想缓存的html，无论怎么设置，还是被CacheWebView缓存了下来。
2、想缓存的webp，设置后的确缓存下来了，可出现了一个令人窒息的问题，webp的缓存有概率会不可用。
一百多张图片，有时运气好，全部从本地缓存加载了，有时运气不太好，有几十张还得从网络获取，有时运气很不好，一张也没从本地缓存加载出来，全走网络了。
折腾了CacheWebView半天，实现出来的东西并不能让人满意，稳定性非常差。在某些机型上甚至出现了首次从网络获取到图片后，再也加载不出图片的问题。
最后结合CaCheWebView图片堵塞的思路，自己开了下脑洞，在原生WebView上几行代码便实现了仅缓存图片的功能。
供参考：http://m.blog.csdn.net/qq_35813887/article/details/78966907

**Comment by yale8848** [comment]
1,html是缓存了，更新方式是通过http缓存字段控制更新；
2,webp未缓存应该和网络有关系，或者和你设置缓存大小有关系；
图片堵塞的思路确实很棒，但是默认缓存空间有些小。我看你再onPageFinished后加载图片，并缓存，不太确定你真实的需求是啥？

**Comment by 1398113530** [comment]
webp已经全部成功缓存到本地了，但不一定能成功从本地取出来。
这一点在离线下验证，不断离线刷新，有时图片全都加载成功，有时一部分成功，有时一个也不成功。

**Comment by 1398113530** [comment]
在有网络的情况下就表现为，虽然webp已经全部缓存到本地了，但因为可能会发生取不出来的情况，取不出来的那部分图片，就又走网络获取了。
有的安卓手机，取不出来甚至走网络获取都不走，图片直接丢失了。

**Comment by yale8848** [comment]
普通图片你有试过吗？可能和webp的渲染有关系，我这再测试测试

**Comment by mix-future** [comment]
像你这样没有测试链接的问题，别人真的很难分析原因。个人猜测，可能你的部分图片网址不标准，根本没有后缀名，导致其实没有进入自定义缓存，而是进入了原生缓存，而原生缓存容量有限，就发生了部分图片被挤出缓存的情况

**Comment by yale8848** [comment]
@1398113530 麻烦提供个链接吧，我这边方便测试

**Comment by 1398113530** [comment]
http://t.xkspbz.com

**Comment by yale8848** [comment]
@1398113530 你更新至1.3.4试试；
1. 默认添加了webp后缀；
2.解决了如果url中有特殊字符获取后缀失败的问题，你这个链接中的有些webp路径有特殊字符导致获取失败而不能缓存；
