### ISSUE TITLE
速度问题

### ISSUE THREAD

**Issue by windworst** [yale8848/CacheWebView#38]
实测在shouldInterceptRequest中拦截request 打开网页的速度会比正常情况慢得多。
原因是因为浏览器使用单线程调用shouldInterceptRequest，而正常情况下浏览器使用多线程加载。

**Comment by yale8848** [comment]
如果加上预加载的话应该也是很快的，毕竟从本地获取资源比从服务器端获取资源要快很多；
你可以看看 [#7](https://github.com/yale8848/CacheWebView/issues/7) 我这边测试的结果；
