### ISSUE TITLE
又发现一个乱码的网站

### ISSUE THREAD

**Issue by 418623336** [yale8848/CacheWebView#4]
http://www.ranwena.com/files/article/1/1268/5028890.html
 这个网站的小说正文乱码，大大周末有空看看怎么回事呢？（编码问题好头疼，完全搞不懂原理……）

**Comment by 418623336** [comment]
源码里明明看了很正常的文字，编码也很常规，，就是搞不懂为什么会乱码……

**Comment by 418623336** [comment]
对了，我用之前1.0.1的版本测试是不乱码的

**Comment by 418623336** [comment]
又发现一个乱码的，http://m.lewen8.com/lw2408/2030224.html 跟前面一个乱码的格式还不太一样

**Comment by yale8848** [comment]
你用最新的库，调用
setEncodeBuffer(1024),我新版本默认是500，有些小，你设置成1024应该就没有问题了

**Comment by 418623336** [comment]
谢谢啊，刚想起来问题还没关闭，现在确实没有乱码了～～

**Comment by yale8848** [comment]
没事，今天把有些接口改了，你注意一下
