### ISSUE TITLE
为什么CacheWebView 的预加载一定要在UI线程中执行,能不能在子线程中执行? 你提供的在服务中下载无效

### ISSUE THREAD

**Issue by Xujun770366270** [yale8848/CacheWebView#40]
CacheWebView.cacheWebView(MyAcitivity.this).loadUrl(mPathList.get(prePage));

可不可以设置能在子线程中执行

**Comment by yale8848** [comment]
webview不能在子线程中执行，不然就会报错，你可以调用CacheWebView.servicePreload(this,URL); 在service中执行
