### ISSUE TITLE
请问一下,能不能增加预加载完成监听,这样,是否预加载玩,用户都可以知道

### ISSUE THREAD

**Issue by Xujun770366270** [yale8848/CacheWebView#41]
希望大哥能加以一下,同时能否可以增加动态修改缓存地址的方法

**Comment by yale8848** [comment]
可以增加预加载监听，但是不知道“增加动态修改缓存地址的方法”的目的什么？

**Comment by Xujun770366270** [comment]
嗯嗯,我向请问一下博主,是否能增加一个预加载成功与否的监听  ,不知道能否加博主的一个微信或者QQ,我的微信号是xj770366270

**Comment by yale8848** [comment]
你加我qq吧：314316537
