### ISSUE TITLE
预加载不了,一直报错

### ISSUE THREAD

**Issue by Xujun770366270** [yale8848/CacheWebView#42]

**Comment by yale8848** [comment]
麻烦贴上代码和链接看看，下面的信息最好都贴出来：
Mobile:

Android OS:

NetWork:

URL:

LIB Version:

**Comment by Xujun770366270** [comment]
大哥预加载的问题是我传的URl为null问题,这个预加载是可以的,但是预加载的时候我发现一个问题,如果预加载的时候我正在预加载一个网页,还没有加载完,此时我去预加载另一个网页,此时会出现前一个网页预加载会不成功,有部分资源可能没有预加载到本地

**Comment by yale8848** [comment]
这个问题我还没有测试，我当初考虑到性能问题以及当时的需求，最好只预加载一个最常用的链接，要不然会体验不好；

**Comment by Xujun770366270** [comment]
这个我们是准备实现一个网页的下载功能,, 如果我们需要缓存多个网页任务,那么我们是准备使用缓存的方式下载,把网页的类容缓存到本地, 每次要使用,就对缓存进行管理, 另外,博主是否能加个页面缓存成功与否的监听,这个我们需要使用,  另外如果有可能的话,还请博主提供一个对缓存的地址动态更改的功能,这样便于对缓存进行管理,   另外我刚才测试,好像缓存地址不能更改到内存卡路径,只能是应用当前的缓存路径

**Comment by yale8848** [comment]
1.页面缓存成功与否的监听这个可以加
2.对缓存的地址动态更改 这个你看通过这个下面方式获取缓存文件能满足你的需求不：
```
CacheStatus cacheStatus =  webview.getWebViewCache().getCacheFile(URL);
 if (cacheStatus.isExist()){
    File file = cacheStatus.getCacheFile();
    String extension = cacheStatus.getExtension();
 }
```
3.不能更改到内存卡路径 这个应该和权限配置有关系

**Comment by Xujun770366270** [comment]
![image](https://user-images.githubusercontent.com/13106539/34780047-f84afbf2-f65c-11e7-90f5-159af78a4222.png)
你的这个extension 是什么意思

**Comment by yale8848** [comment]
extention是文件后缀名，你用一下就知道了

**Comment by Xujun770366270** [comment]
大哥你好,预缓存的时候,这个cachewebview 有的时候并不能立马缓存,需要等好久才缓存, 我是通过缓存日志观察

**Comment by yale8848** [comment]
你是用service启动的吗？

**Comment by Xujun770366270** [comment]
![image](https://user-images.githubusercontent.com/13106539/34804740-3116b11c-f6b5-11e7-8a86-5103a769dd19.png)

博主你好,不知道您能否简化一下日志输出,我做测试的时候发现有很多无用的日志,我建议博主可以简化一下

**Comment by Xujun770366270** [comment]
![image](https://user-images.githubusercontent.com/13106539/34806541-8460e3f2-f6be-11e7-8f58-8e5b9923fa11.png)
另外我 建议,博主是否可以把预缓存的方式(你放在服务中进行的方式),我建议不要放在服务里面执行,这个放在哪执行,最好是交个用户,因为由你来处理服务,可能有很多其它情况会导致你的server 会有问题

**Comment by yale8848** [comment]
1.日志用来debug的，这个可以简化，release你可以可以混淆掉；
2.虽然我开了再服务器执行的接口，但你可以依然可以自定义预加载；

**Comment by Xujun770366270** [comment]
如何使用大哥的预加载功能,我想放在不同的线程中执行,你的有一个预加载方法是不能放在子线程中执行,另外一个难道是把server 放在子线程中执行?

**Comment by yale8848** [comment]
webview不能在子线程中执行，只能再UI线程中执行，要不然直接报错

**Comment by mix-future** [comment]
WebView是没有办法在其他线程里执行的。预加载其实就是把资源给缓存到WebView的内存缓存里，你可以考虑单独建一个网页，把要加载的css,js,图片资源全放到里面去让WebView加载。如果是html文件，你可以在子线程里直接下载下来，然后用loaddatawithbaseurl的方式加载，这样速度比loadurl方式要快，baseUrl和historyurl就用对应html的url网址。

**Comment by yale8848** [comment]
谢谢 @mix-future 提示

**Comment by Jiiiiiin** [comment]
```java
public void loadUrl(String url){
        if (url.startsWith("http")){
            mCacheWebViewClient.addVisitUrl(url);
        }
        super.loadUrl(url);
    }
```
源码里面有上面这样的代码，如果是https会如何，在我进行：
```java
CacheWebView.cacheWebView(this).loadUrl(BaseConfig.getUrl(BaseConfig.URL_FINANCE_URL));//要放在UI线程
```
的时候，跟到；

**Comment by yale8848** [comment]
麻烦把问题描述清楚一下，谢谢

**Comment by Jiiiiiin** [comment]
ren.yale.android.cachewebviewlib.CacheWebView 132行，最新版本，请看一下。

**Comment by Jiiiiiin** [comment]
@yale8848 我的意思是你这行代码`if (url.startsWith("http")){`这样判断，那么针对于https那就不做处理，原因是什么？

**Comment by Jiiiiiin** [comment]
@yale8848 我的意思是你这行代码`if (url.startsWith("http")){`这样判断，那么针对于https那就不做处理，原因是什么？

**Comment by yale8848** [comment]
https也是包含http呀

**Comment by Jiiiiiin** [comment]
我错了 这么省事，阔以阔以
