### ISSUE TITLE
image caching issues

### ISSUE THREAD

**Issue by issuerapota** [yale8848/CacheWebView#48]
Mobile:  All phone
Android OS: 8.0
NetWork: WiFI/3G/4G/5G
URL: Page with big image
LIB Version:  ren.yale.android:cachewebviewlib:1.3.5
---
i have a problem with the current method of caching.
it cause corrupted image when you close **unfinished page**.
because the webview still caching the image before it completed.
this problem isn't exist on default webview.

**Comment by yale8848** [comment]
can you apply htmlData?

**Comment by issuerapota** [comment]
@yale8848 it can happen on all pages with big images

replicating
```
btn1.setOnClickListener(View.OnClickListener {
// load page with big image
    webView.loadUrl("https://www.wallpaperflare.com/static/820/723/599/erratics-golden-hour-scotland-highlands-wallpaper.jpg")
})
btn2.setOnClickListener(View.OnClickListener {
// interrupt it from finishing (will save incomplete image to disk)
    webView.loadUrl("about:blank")
})
btn3.setOnClickListener(View.OnClickListener {
// clearing cache to replicate
    webView.loadUrl("about:blank")
// clearCache doesn't work when the page still open
    webView.clearCache()
})
```

Log
```
D/CacheWebView: visit https://www.wallpaperflare.com/static/820/723/599/erratics-golden-hour-scotland-highlands-wallpaper.jpg
D/CacheWebView: disk cached https://www.wallpaperflare.com/static/820/723/599/erratics-golden-hour-scotland-highlands-wallpaper.jpg
```

**Comment by yale8848** [comment]
update to 1.3.6 then try it again

**Comment by issuerapota** [comment]
Thanks but the issue wasn't about the clearCache() it was fine the way it is on 1.3.5, the issue is come from ResourseInputStream class.
this is why it's still caching interrupted image.

**Comment by yale8848** [comment]
ok, get it , try to update to 1.3.7 and try it again

**Comment by issuerapota** [comment]
well done, thank you very much it does **fix** the issue.
also please set private void initSettings() to
```
webSettings.setSupportZoom(true);
```
it wont enable zooming by itself, but it's needed to enable zooming.
to make it work just like default webview, so people doesn't need to write it every single webview

and please revert clearCache() to 1.3.5 version
```
public void clearCache(){
        CacheWebViewLog.d("clearCache");
        FileUtil.deleteDirs(mAppCachePath,false);
        mWebViewCache.clean();

    }
```
these lines doesn't help clearing cache
```
CacheWebViewLog.d("webview stopLoading");
this.stopLoading();
```
Thanks, feel free to close the issue

**Comment by yale8848** [comment]
1. CacheWebView extends WebView you can call webSettings by yourself.
2. If WebView still working , some files will locked, so clearCache delete files will fail, so stopLoading before clearCache will be more safe.
