### ISSUE TITLE
你好, 我就想问2个问题

### ISSUE THREAD

**Issue by HeSuxiang** [yale8848/CacheWebView#51]
Mobile:  coolpad7230 
Android OS: 4.2

NetWork: WiFI

URL: asset的html加在线图片

LIB Version:  1.3.7

---

我基础比较差, 你的代码看不怎么懂, 好像没看到开线程下载缓存资源啊, 
还有我用你的库的时候, 我assets里面有内置的html, 里面的图片是在线的url, 
我加载的时候发现内置的html也要很久才出来, 我设置了先不加载图片也是一样
而且页面变的很宽, 就好像打开了一个电脑版网页一样

我本来想自定义缓存, 看了很多资料, 但是卡在最后shouldInterceptRequest的返回里面了, 当我没有缓存的资源时, 我就去开线程下载,然后存进缓存里面, 下载完毕却不知道怎么让shouldInterceptRequest返回资源了,因为下载完毕时我在线程里面了, 请问你是怎么解决这个问题的, 谢谢!

**Comment by HeSuxiang** [comment]
第二个问题答案是强制缓存吗, 不好意思

**Comment by yale8848** [comment]
CacheWebView拦截资源后并没有开启新线程去下载，http请求资源时先建立连接，然后通过InputStream来获取具体资源流（资源数据），也就是说每次获取资源时大部分时间都浪费在InputStream流获取上了，所以WebView一般把建立连接（很快）会放在单独线程，而把InputStream获取上会放在不同的线程上（耗时操作）。
    所以你会看到getWebResourceResponse返回WebResourceResponse的中把InputStream也封装起来了，也就是说CacheWebView的资源加载的多线程问题和系统WebView的多线程是一致的。
    不同系统下WebView实现不一样，有些是多线程，有些是单线程(老系统，硬件受限)，你可以测试测试OS7.0 Android 系统WebView线程情况。
    如果自己要实现多线程，我可以提供一种思路：
    1.WebView加载完后自己解析html提取要缓存的资源路径，然后多线程下载；
    2.自己实现类似CacheWebView中的ResourseInputStream，系统在回调read( byte[] b, int off, int len)时，你再从你缓存中拿数据即可；

**Comment by HeSuxiang** [comment]
!^! , 你好, 你说的都好难啊, 我看我还是拦截资源后让浏览器自己去加载, 然后再去我同时再去下载缓存一次图片, 就是会浪费流量

**Comment by yale8848** [comment]
webview 加载资源会在新的线程里，不会阻碍UI线程；
如果你这样做确实会浪费一些流量了；

**Comment by HeSuxiang** [comment]
webview 加载资源会在新的线程里, 哇, 原来这样, 谢谢大神!
