### ISSUE TITLE
你好，给个建议

### ISSUE THREAD

**Issue by mf1564662361** [yale8848/CacheWebView#54]
库内部调用webview 和webclient 的地方 最好抽成一个 interface 可以自定义 实现类 用别的webview   我现在项目用的是腾讯的webview 要去你源码修改包名  这样库的耦合性太高了

**Comment by yale8848** [comment]
谢谢提议，当初直接继承webview就是为了调用者方便使用，但是这样确实会有你说的问题存在，回头我把主要逻辑抽出来，然后和webview解耦；

**Comment by mf1564662361** [comment]
嗯嗯，其实你一开始可以不用直接继承   直接抽象出来 然后给个默认的实现类就是系统默认的webview 然后在提供可以自定义的方法 如果开发者有需要就可以自定义 没有需要就是默认的实现

**Comment by Jiiiiiin** [comment]
也可以考虑弄一个x5的版本，因为默认就原生自动实现和x5实现还比较稳定，这样的话，方便开发者集成，便于项目推广。 呵呵
谢谢作者

**Comment by yale8848** [comment]
嗯嗯 说的有道理，谢谢啦

**Comment by Jiiiiiin** [comment]
我们正在使用，今天还给你反馈了几个问题，呵呵，希望有时间帮忙看看。@yale8848
