### ISSUE TITLE
缓存文件有时候不存在

### ISSUE THREAD

**Issue by AnJiuZhe** [yale8848/CacheWebView#55]
你好，我想获取webview已经缓存好的图片，但是有时候该文件不存在，请问是什么原因呢？

CacheStatus cacheStatus = mCacheWebView.getWebViewCache().getCacheFile(url);
 if (cacheStatus.isExist()) {
           Intent intent = new Intent(context, ImageActivity.class);
           context.startActivity(intent);
           EventBus.getDefault().postSticky(new WebViewImagClickEvent(cacheStatus.getCacheFile()));
  }

**Comment by yale8848** [comment]
麻烦发一下具体网址和你关键操作的代码

**Comment by AnJiuZhe** [comment]
我加载的是jsoup抓包获取的html片段，里面包含图片地址，我想点击webview中的后图片浏览。
![image](https://user-images.githubusercontent.com/30287547/37692172-f9c176d4-2cf1-11e8-9520-93f87ea7b46f.png)
![image](https://user-images.githubusercontent.com/30287547/37692177-04ac8fe8-2cf2-11e8-9d96-009b0aed9784.png)

**Comment by yale8848** [comment]
你看一下log里这个图片url缓存成功了没？TAG=CacheWebView

**Comment by AnJiuZhe** [comment]
第一张是点击不能查看图片的log，第二张是点击可以查看的log
![image](https://user-images.githubusercontent.com/30287547/37692508-1e263404-2cf4-11e8-9fbf-b534da79f803.png)
![image](https://user-images.githubusercontent.com/30287547/37692510-26ee934c-2cf4-11e8-8a07-f68c1a8b21ac.png)

**Comment by AnJiuZhe** [comment]
在activity的ondestroy中我调用了clearcache方法，第一次进入activity可以查看图片，销毁再次进入的时候
图片不能查看，而且没有打印下面这条日志
![image](https://user-images.githubusercontent.com/30287547/37692655-0b6572f2-2cf5-11e8-8a64-25527d12eefa.png)

**Comment by yale8848** [comment]
你把你html data发一下，我这边测测看看

**Comment by AnJiuZhe** [comment]
沃视频～发现～顶部广告领取

<br>共有1个附件(扣50个妖晶):
<br>
<div class="line">
 1.screenshot_2018-03-21-10-22-54-916_com.unicom.woshipin.png(475.9KB)
 <br>
 <a href="/bbs/picDIY.aspx?siteid=1000&classid=201&id=600811&path=bbs%5cupload%2f1000%2f2018%2f03%2f21%2f32873_1025080screenshot_2018-03-21-10-22-54-916_com.unicom.woshipin.png"><img src="/bbs/upload/1000/2018/03/21/32873_1025080screenshot_2018-03-21-10-22-54-916_com.unicom.woshipin.png" width="400px" alt="screenshot_2018-03-21-10-22-54-916_com.unicom.woshipin"></a>
 <br>
 <br>
</div>

**Comment by AnJiuZhe** [comment]
[新建文本文档.txt](https://github.com/yale8848/CacheWebView/files/1831943/default.txt)

**Comment by yale8848** [comment]
你更新到1.3.9再试试

**Comment by Jiiiiiin** [comment]
@yale8848 2.0啥时候开始重构呀 哈哈

**Comment by yale8848** [comment]
@Jiiiiiin 最近工作忙，得有空了再重构，如果缓存有问题，你先屏蔽掉预加载，让程序先正常运行

**Comment by Jiiiiiin** [comment]
理解理解 忙完我也拜读一下，真去贡献pr

**Comment by yale8848** [comment]
拜读啥，我写的代码也很糟糕的，相互学习么
