### ISSUE TITLE
如何设置缓存时长

### ISSUE THREAD

**Issue by mustYudh** [yale8848/CacheWebView#58]
缓存失效时长如何设置

**Comment by yale8848** [comment]
如果是强制缓存，那就让后台换链接，比如说加md5值
如果没有强制缓存，目前只能让后台给静态资源添加缓存字段，https://www.cnblogs.com/vajoy/p/5341664.html 可以看看这里

**Comment by songfeibeijing** [comment]
![image](https://user-images.githubusercontent.com/23418383/38544121-2c68413e-3cd9-11e8-837c-7528a88480b3.png)


抱歉哈  我没看明白  这两块说的是   要删除  webview   还是删除 缓存文件中  对应结尾的缓存资源？？？

是必须要添加的吗  ？？？

**Comment by scsfwgy** [comment]
是否可以支持缓存的最大时长？比如计算缓存一周，一周后自动失效；或者支持一个标准的header（ex:no-chace）,当取到这个header的时候令这个强制缓存失效？
@yale8848

**Comment by yale8848** [comment]
缓存时长控制建议还是按照标准的http缓存协议，由后台控制更加合理些，前端不建议做这些设置

**Comment by scsfwgy** [comment]
但是如果我们设置强制加载缓存后，后台的设置不就没有效果了吗？我的意思是可以做一些兼容，兼顾强制加载。
