### ISSUE TITLE
和安卓原生的WebView相比，CacheWebView加载出来的页面感觉被放大了。

### ISSUE THREAD

**Issue by hxzhang01** [yale8848/CacheWebView#60]
我是在安卓5.0下测试的。用CacheWebView和系统原生的WebView加载同一个页面，CacheWebView在字体和图片上的显示都比原生WebView的大，感觉像是被缩放了130%左右的样子，请问是什么原因呢？

**Comment by yale8848** [comment]
你修改WebSetting的配置了吗？

WebSettings webSettings = webview.getSettings();
 settings.setUseWideViewPort(true); 
 settings.setLoadWithOverviewMode(true);

**Comment by hxzhang01** [comment]
确实是WebSetting配置的问题
