### ISSUE TITLE
关于缓存的问题

### ISSUE THREAD

**Issue by raulbest** [yale8848/CacheWebView#63]
这个自定义的WebView是不是在有网络的情况下就不走缓存了，直接去请求数据了？

**Comment by yale8848** [comment]
首先CacheWebView只对静态资源缓存(html,js,css,png,jpg等等)，不会对post数据，后台动态数据(json数据)缓存；
如果设置了WebViewCache.CacheStrategy.FORCE 强制缓存的话有网无网都走缓存，如果没有设置强制缓存，那就看你服务器配置的http缓存策略了

**Comment by raulbest** [comment]
弱网络环境下，每次点进来的加载都很慢，感觉好像是没走缓存，这个是什么原因呢？设置的话是参考你demo中的Main2Activity中设置的

**Comment by yale8848** [comment]
webview.setCacheStrategy(WebViewCache.CacheStrategy.FORCE); 试试，这个我问题可能是非静态内容加载慢造成的
