### ISSUE TITLE
支持缓存https吗

### ISSUE THREAD

**Issue by 1762588562** [yale8848/CacheWebView#66]
支持缓存https吗

**Comment by yale8848** [comment]
支持

**Comment by 1762588562** [comment]
Application中设置了
 File cacheFile = new File(this.getCacheDir(),"cache_path_name");
CacheWebView.getCacheConfig().init(this,cacheFile.getAbsolutePath(),1024*1024*100,1024*1024*10)
.enableDebug(true);
Webview中设置了
webview.setCacheStrategy(WebViewCache.CacheStrategy.NO_CACHE);
但是还是会从服务端请求js 更资源 ,还需要怎么做吗？

**Comment by 1762588562** [comment]
Application中设置了
File cacheFile = new File(this.getCacheDir(),"cache_path_name");
CacheWebView.getCacheConfig().init(this,cacheFile.getAbsolutePath(),10241024100,1024102410)
.enableDebug(true);
Webview中设置了
webview.setCacheStrategy(WebViewCache.CacheStrategy.NO_CACHE);
但是还是会从服务端请求js 等资源 ,还需要怎么做吗？

**Comment by yale8848** [comment]
代码里将WebView改为CacheWebView或者layout xml里修改WebView为ren.yale.android.cachewebviewlib.CacheWebView 这个修改了吗？
