### ISSUE TITLE
怎么设置让html也走强制缓存？

### ISSUE THREAD

**Issue by Lester-lin** [yale8848/CacheWebView#67]
Mobile:  

Android OS: 

NetWork: 

URL: 

LIB Version: 

---

**Comment by yale8848** [comment]
我这边设计html不支持l强制缓存，原因如下：
有些html内容是会改变的，如果强制缓存会无法更新，比如说很多ww.xxx.com/index.html，这个路径不会变的；
不强制缓存不是不缓存，其实是缓存html的，只是多了一步和服务器沟通，如果没有更新html走304后还是用缓存的html

**Comment by Lester-lin** [comment]
我这边使用过程中发现一个问题，使用强制缓存模式，开始的时候index.html,js,css,jpg等都缓存下来了，但是过一段时间，发现index.html没有读取缓存，里面的js,css,jpg等也都重新从服务器请求，我保证服务器 index.html肯定没修改过。这是什么问题呢？

**Comment by yale8848** [comment]
1.是不是清除缓存了；
2.缓存目录大小太小，老的文件就回被清除掉了；

**Comment by Lester-lin** [comment]
没有清，缓存目录200M呢，肯定足够的，多次测试进入的都是同一画面，没多少缓存的。

**Comment by yale8848** [comment]
请提供一下测试url

**Comment by taojie** [comment]
我的也是缓存过一会就清了，就剩下一个journal文件，其他都没了

**Comment by yale8848** [comment]
@taojie 麻烦提供一下测试的url

**Comment by jhwsx** [comment]
如果 html 不能设置强制缓存, 那么即便是预加载了, 还是会继续和服务器交互, 这样在网络比较差时体验还是有点慢啊.

**Comment by yale8848** [comment]
你说的这种情况存在的；
如果html强制缓存，那更新html就是问题，比如说一个url：http://xxxx.com/index.html  如果强制缓存index.html，那index.html内容就无法更新了，html文件有可能是个入口，入口是不能变的；不像其它静态资源如js，js文件路径可以锁死不变，强制缓存是没有问题的；
以上是我设计时考虑的情况；

**Comment by jhwsx** [comment]
确实是, 有利有弊. 我这里的情况是展示 h5 详情的文章, 里边的内容编辑好后还是很固定的. 现在, 产品提出缓存好的文章, 进去之后还是很慢的问题. 我现在的解决办法是在遇到 .html 时也强制加载. 当然, 我得把弊端也告诉他们.

**Comment by yale8848** [comment]
嗯嗯 好吧
