### ISSUE TITLE
建议增加预加载资源

### ISSUE THREAD

**Issue by xinfangke** [yale8848/CacheWebView#68]
建议增加预加载资源。

大多数情况，如游戏，网站等，都需要在APP第一次安装时，预先装载部分资源。

是否增加assets中都资源装载到缓存区

**Comment by yale8848** [comment]
嗯 ，这个需求我之前考虑过，下个大版本我把这个功能加上；

**Comment by Jiiiiiin** [comment]
这个功能比较牛哦
