### ISSUE TITLE
加载速度

### ISSUE THREAD

**Issue by zhaowangdaren** [yale8848/CacheWebView#7]
为什么连续打开、关闭某个网页，第三次或者往后，原始的webview加载的速度要比cacheView快，前者几乎秒开，为什么CacheWebView的速度会慢？

**Comment by yale8848** [comment]
能否把测试的相关信息说一下：
手机型号
Android OS版本
测试URL地址

**Comment by zhaowangdaren** [comment]
手机型号：xiaomi note 4x
OS: miui global 9.0       android 7.0
网络：Wi-Fi
测试URL：http://element-cn.eleme.io/#/zh-CN
测试结果：
   连续仿佛关闭打开页面，普通webView加载完成的耗时稳定在800ms左右，CacheWebView稳定1000+ms。
测试代码：
  为源码中的Main2Activity，将第26行的clearCache注释掉

**Comment by yale8848** [comment]
> 手机型号：xiaomi 5 
  OS: 7.0
  网络： WIFI
   测试URL：http://element-cn.eleme.io/#/zh-CN 
   库：ren.yale.android:cachewebviewlib:1.2.2

### 有网测试10次

| WebView+默认缓存(毫秒) | CacheWebView+强制缓存(毫秒) |
|:-:|:-:|
|2012|1949|
|1852|1410|
|1922|1944|
|2069 |1458|
|1799 |1581|
|2047 |1452|
|1836 |1528|
|1976 |1347|
|1511 |1669|
|1346 |1609|
|平均:1837|平均:1595|

### 无网
| WebView+LOAD_CACHE_ELSE_NETWORK | CacheWebView+强制缓存 |
|:-:|:-:|
|无法访问|正常访问|
