### ISSUE TITLE
能否提供全局WebView的方案？

### ISSUE THREAD

**Issue by ChaserSheng** [yale8848/CacheWebView#72]
谢谢作者的库，对于加载是提升了不少速度，但是初始加载的时候还是有白屏时间。我搜索了相关文章，有介绍说是可以全局一个webview，首先预加载index.html，然后通过通过路由跳转具体页面，页面关闭时，webview回到index.html页面。我也做了测试，效果是会好很多，但是发现在回退，js调用出现了一些问题，内存占用也很大，作者能否写一个这方面的解决方案，谢谢。

**Comment by yale8848** [comment]
全局一个webview的方案是个不错的方案，这样可以有效的解决首屏白屏的问题，但是对于多个webview同时要处理时就比较麻烦了，或者对于index.html有变化需求时也不好处理，所以我开始就放弃了这个方案；其实CacheWebView也有预加载，也可以减少白屏时间，就是没有全局webview效果好；
还有，回退时js调用出现了一些问题，这块能你能分享一下具体是啥问题吗？

**Comment by leveychen** [comment]
我把webview放到独立的进程里面，在Application里面用空的service去启动，这样webview流畅度和加载速度都比在主进程好很多。全局一个webview局限性很大，有些不方便。有没有更好的思路分享一下？

**Comment by yale8848** [comment]
@leveychen 谢谢分享，你把webview放入单独进程是个好思路，如果要预加载的话，这样基本够用了，把你能预先知道的url放在webview进程里挨个访问一遍，或者给service把url发过去，让其提前加载，这样可以有效减少白屏和加载速度；
