### ISSUE TITLE
addJavascriptInterface方法失效

### ISSUE THREAD

**Issue by Kenmmm** [yale8848/CacheWebView#73]

**Comment by yale8848** [comment]
声明注解 @JavascriptInterace 了吗？

**Comment by Kenmmm** [comment]
换成cachewebview 就不行，用 webview 就可以。。

**Comment by yale8848** [comment]
我这里测试没有问题啊，你调用 webSettings.setJavaScriptEnabled(false) 了吗？请贴一贴关键代码
