### ISSUE TITLE
WebViewClient的两个方法不停调用

### ISSUE THREAD

**Issue by arkilis** [yale8848/CacheWebView#79]
Mobile:  锤子手机-坚果Pro2 

Android OS: 7.0

NetWork: 4G 

URL: https://www.baidu.com

LIB Version: ren.yale.android:cachewebviewlib:1.2.2

---

WebViewClient的两个方法不停调用，日志大量输出. 确认 link中没有 http redirect. 谢谢

```
7-17 17:17:31.402 7345-7345/com.example.prod D/SunSuperWebViewClient: Web View Started
07-17 17:17:31.582 7345-7345/com.example.prod D/SunSuperWebViewClient: Web View Started
07-17 17:17:31.589 7345-7345/com.example.prod D/SunSuperWebViewClient: Web View Loaded : https://secure.example.com.au/MemberOnline/MobileApp/Member/Statements?ItemsPerPage=10&Page=1&yearFilter=2016&yearFilter=2015
07-17 17:17:31.590 7345-7345/com.example.prod D/SunSuperWebViewClient: Web View Started
07-17 17:17:31.721 7345-7345/com.example.prod D/SunSuperWebViewClient: Web View Started
07-17 17:17:31.732 7345-7345/com.example.prod D/SunSuperWebViewClient: Web View Loaded : https://secure.example.com.au/MemberOnline/MobileApp/Member/Statements?ItemsPerPage=10&Page=1&yearFilter=2016&yearFilter=2015
```

**Comment by yale8848** [comment]
1.如果你用的还是1.x.x 那就切换到最新的1.4.0试试；
` D/SunSuperWebViewClient: Web View Loaded : https://secure.example ...`这一句是在什么地方log的？
2.2.0.0 已经发布了，建议可以用最新版本，2.0.0不兼容1.x.x

**Comment by arkilis** [comment]
感谢你的回复

这些日志在：

```java

public void onPageStarted(final WebView view, String url, Bitmap favicon) {
// log
}

public void onPageFinished(WebView view, String url) {
// log
}
```
`WebViewClient`

**Comment by arkilis** [comment]
2.0.0的去掉了以前一些比较好的features.

之前的版本，能用 CacheWebView 进行资源的预处理，即先利用service缓存html，css等静态资源，然后等需要的时候，可以进行快速加载。

现在的版本更多的是对现有的或者已经浏览的网页进行自动缓存。

**Comment by yale8848** [comment]
2.0.0 主要是解耦了和WebView的依赖，缓存只关注缓存，这样对于调用者可以有更灵活的操作；
如果要预处理，可以自己实现service缓存，代码量也不大；

**Comment by arkilis** [comment]
@yale8848 

Correct me if I am wrong but the correct answer to this question is that there is NO possible way to use a WebView in the background while the user is doing other things on the phone without interrupting the user by means of an Activity.

I have applied both Randy and Code_Yoga's suggestions: Using an activity with "Theme.NoDisplay" to launch a background service with a WebView to do some work. However even though no view is visible the switching to that activity for that second to start the services interrupts the user (ex. like pausing a running game that was being played).

Totally disastrous news for my app so I am still hoping someone will give me a way to use a WebView that does not need an Activity (or a substitute for a WebView that can accomplish the same)

https://stackoverflow.com/questions/18865035/android-using-webview-outside-an-activity-context

**Comment by yale8848** [comment]
webview必须在主线程初始化和调用。
IntentService是开启了新线程，在IntentService 中调用webview肯定是有问题，你可以在普通service中初始化和调用，之前1.x版本就是这么实现的；
