### ISSUE TITLE
缓存模式增加几种？

### ISSUE THREAD

**Issue by LuoGuoXin** [yale8848/CacheWebView#88]
我看到缓存模式只有2种，正常和强制缓存。
正常，应该就是不缓存吧？
强制缓存，就是每个页面都会自动缓存？

有这种缓存模式吗？打开一个链接，如果之前没打开过（没缓存），就正常打开，并且缓存下来。等下一次，再进入这个网页，这时候是有缓存了，就直接显示缓存的页面，同时加载更新网页，等加载网页完了再设置显示，覆盖掉缓存。这样，就实现，秒开然后再更新界面的效果。

**Comment by yale8848** [comment]
1.目前只有正常和强制缓存，默认是强制缓存，用这个库的目的就是要缓存么；
2.强制缓存只缓存静态资源，如.js，.css等，对于.html不强制缓存，但也缓存，.html缓存策略是http的默认缓存策略；其他动态内容不缓存；
3.目前你说的覆盖掉缓存模式这个库暂没有实现，你可以参考腾讯的：https://github.com/Tencent/VasSonic  这个库就是这么实现的；
