### ISSUE TITLE
builder.setSSLSocketFactory(sslSocketFactory,x509TrustManager);设置证书没用

### ISSUE THREAD

**Issue by 994866755** [yale8848/CacheWebView#91]
try {
            X509TrustManager x509TrustManager =  new X509TrustManager() {
                @Override
                public X509Certificate[] getAcceptedIssuers() {
                    return new X509Certificate[]{};
                }

                @Override
                public void checkClientTrusted(X509Certificate[] chain,
                                               String authType) throws CertificateException {

                }

                @Override
                public void checkServerTrusted(X509Certificate[] chain,
                                               String authType) throws CertificateException {

                }
            };
            SSLContext sslContext = SSLContext.getInstance("SSL");
            sslContext.init(null, new TrustManager[]{x509TrustManager}, new SecureRandom());
            SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();
            builder.setSSLSocketFactory(sslSocketFactory,x509TrustManager);//自定义SSLSocketFactory和X509TrustManager
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (KeyManagementException e) {
            e.printStackTrace();
        }

我在okhttp跳过证书的时候是这样写的，在这里这样写会报Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. 还是展示https的页面

**Comment by yale8848** [comment]
builder.setTrustAllHostname(); 试试

**Comment by 994866755** [comment]
我在WebViewClient重写onReceivedSslError方法解决了，谢谢
