### ISSUE TITLE
2.0.2版本如何使用预加载?

### ISSUE THREAD

**Issue by whmain** [yale8848/CacheWebView#96]

**Comment by yale8848** [comment]
2.x不提供预加载功能，你可以自己实现，这样更灵活

**Comment by whmain** [comment]
好的，谢谢

**Comment by whmain** [comment]
另外，想在请问下我在去Application中移除了html和js的缓存，但为何下次打开同样页面时，并没有重新下载html和js文件呢

**Comment by yale8848** [comment]
你意思是在Application中调用WebViewCacheInterceptorInst.getInstance().clearCache() 了吗？
