### ISSUE TITLE
关于缓存是否设置成功

### ISSUE THREAD

**Issue by fly803** [yale8848/CacheWebView#97]
从GitHub下载了示例代码，如果设置缓存成功是不是关掉网络也能访问网络呢，为什么我试了关掉网络不能继续访问呢，还有就是不关闭网络，请求请求过的网站并没有觉得变快呢？

**Comment by yale8848** [comment]
CacheWebView 注意只缓存静态资源，对于动态内容，如php，java渲染的页面是不缓存的；你贴一下url，我这边看看
