### ISSUE TITLE
接入第三方SDK后，无法拉起支付（支付宝、微信）页面

### ISSUE THREAD

**Issue by xiangjiabanana** [yale8848/CacheWebView#99]
采用CacheWebView之后就无法拉起第三方支付界面。改回原生WebView就又恢复正常。请问大佬，这种情况，要从哪里着手去解决呢？

**Comment by yale8848** [comment]
你用哪个CacheWebView 版本？

**Comment by xiangjiabanana** [comment]
1.4.0的版本，最新的2.0的版本，都试过

**Comment by yale8848** [comment]
如果你的项目minSdkVersion<21
将调用 mWebView.loadUrl(url) 的地方替换为：WebViewCacheInterceptorInst.getInstance().loadUrl(mWebView,url)

你是这样调用的吗？

**Comment by scsfwgy** [comment]
@yale8848  可以参考以下代码，需要拦截第三方APP的路由，不然就拉不起来。这个可以在你的框架内部处理。


 @Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {
        if (url != null) {
            if (url.startsWith("这里是第三方APP路由跳转的前缀")) {
                //特殊的处理
                try {
                    Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
                    mContext.startActivity(intent);
                    return true;
                } catch (Exception e) {
                    e.printStackTrace();
                    //不要return,继续交给父类处理
                }
            }
        }
        return super.shouldOverrideUrlLoading(view, url);
    }

**Comment by yale8848** [comment]
@scsfwgy 谢谢提示 ，2.0库为了解耦，库里已经不做这些处理了，需要调用者自己实现
